/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/stars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Stars */
        post: operations["parse_stars_api_stars_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Pipeline */
        post: operations["generate_pipeline_api_pipeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule/modify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Modify Schedule */
        post: operations["modify_schedule_api_schedule_modify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_parse_stars_api_stars_post */
        Body_parse_stars_api_stars_post: {
            /** Stars Pdf */
            stars_pdf: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
            current_plan: components["schemas"]["PlanJSON"] | null;
            student_state: components["schemas"]["StudentState"];
            requirements_map: components["schemas"]["RequirementsMap"];
            /** Career Goal */
            career_goal: string;
            /** Hard Courses */
            hard_courses: components["schemas"]["CourseNode"][];
            /** Scored Electives */
            scored_electives: components["schemas"]["ScoredCourse"][];
            /** Scored Enrichment */
            scored_enrichment: components["schemas"]["ScoredCourse"][][];
            other_must_reqs: components["schemas"]["OtherRequirements"];
            /** Ge Placeholders Remaining */
            ge_placeholders_remaining: string[];
        };
        /** ChatResponse */
        ChatResponse: {
            /** Message */
            message: string;
            /** Modify Intent */
            modify_intent: string | null;
        };
        /**
         * ClassLevel
         * @enum {string}
         */
        ClassLevel: "Freshman" | "Sophomore" | "Junior" | "Senior";
        /**
         * CourseNode
         * @description A course required or eligible for inclusion in the student's plan.
         *
         *     Stub form (after hard_courses_node / elective_courses_node):
         *         Only course_code is set. All other fields hold their defaults.
         *
         *     Enriched form (after course_details_retrieval_node):
         *         All fields populated from ChromaDB.
         */
        CourseNode: {
            /** Course Code */
            course_code: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Units
             * @default 0
             */
            units: number;
            /** Prereqs */
            prereqs?: (string | string[])[];
            /**
             * Prereqs Satisfied
             * @default false
             */
            prereqs_satisfied: boolean;
            /** Description */
            description?: string | null;
        };
        /** CourseRecord */
        CourseRecord: {
            /** Semester Label */
            semester_label: string;
            /** Course Code */
            course_code: string;
            /** Units */
            units: number;
            /** Name */
            name: string;
            /** Course Flags */
            course_flags?: string[];
        };
        /** GECategoryStatus */
        GECategoryStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "met" | "unmet" | "in_progress";
            /** Courses Taken */
            courses_taken?: string[];
            /** Courses Needed */
            courses_needed: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OtherRequirements
         * @description Non-course degree requirements derived arithmetically from StudentState.
         */
        OtherRequirements: {
            /** Units Total Required */
            units_total_required: number;
            /** Units Still Needed */
            units_still_needed: number;
            /** Upper Division Required */
            upper_division_required: number;
            /** Upper Division Still Needed */
            upper_division_still_needed: number;
            /** Residency Satisfied */
            residency_satisfied: boolean;
            /** Writing Requirement Satisfied */
            writing_requirement_satisfied: boolean;
            /** Ge Seminar Satisfied */
            ge_seminar_satisfied: boolean;
        };
        /** PipelineRequest */
        PipelineRequest: {
            /** Career Goal */
            career_goal: string;
            student_state: components["schemas"]["StudentState"];
            requirements_map: components["schemas"]["RequirementsMap"];
        };
        /**
         * PlanJSON
         * @description Canonical schedule artifact.
         *
         *     Stored in localStorage after pipeline completion, rendered as the
         *     visual grid, and passed back to schedule_construction_node on re-entry
         *     (as current_plan in AdvisorState / SchedulerState).
         */
        PlanJSON: {
            /** Generated At */
            generated_at: string;
            /**
             * Version Id
             * @default 1
             */
            version_id: number;
            /** Track */
            track: string;
            /**
             * Total Units Planned
             * @default 0
             */
            total_units_planned: number;
            /**
             * Total Semesters
             * @default 0
             */
            total_semesters: number;
            /** Semesters */
            semesters?: components["schemas"]["SemesterPlan"][];
            metadata?: components["schemas"]["PlanMetadata"];
        };
        /** PlanMetadata */
        PlanMetadata: {
            /**
             * Elective Units Placed
             * @default 0
             */
            elective_units_placed: number;
            /**
             * Enrichment Count
             * @default 0
             */
            enrichment_count: number;
            /**
             * Ge Placeholders Placed
             * @default 0
             */
            ge_placeholders_placed: number;
            /** Unresolved Remarks */
            unresolved_remarks?: string[];
        };
        /**
         * PlannedCourse
         * @description A course in the final PlanJSON.
         *
         *     Inherits all CourseNode fields (course_code, name, units, prereqs,
         *     prereqs_satisfied, description) so the validator can access prereqs
         *     directly without unwrapping a wrapper type.
         *
         *     Annotation fields are populated by merge_schedule_node from context —
         *     never by the LLM.
         */
        PlannedCourse: {
            /** Course Code */
            course_code: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Units
             * @default 0
             */
            units: number;
            /** Prereqs */
            prereqs?: (string | string[])[];
            /**
             * Prereqs Satisfied
             * @default false
             */
            prereqs_satisfied: boolean;
            /** Description */
            description?: string | null;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Is Placeholder
             * @default false
             */
            is_placeholder: boolean;
            /**
             * Is Completed
             * @default false
             */
            is_completed: boolean;
            /**
             * Is Enabler
             * @default false
             */
            is_enabler: boolean;
        };
        /** RequirementsMap */
        RequirementsMap: {
            /** Major */
            major: string;
            /** Degree */
            degree: string;
            /** Program Code */
            program_code: string;
            /** Catalog Year */
            catalog_year: string;
            /** Writing */
            writing: (string | string[])[];
            /** General Education */
            general_education: (string | string[])[];
            /** Pre Major Engineering */
            pre_major_engineering: (string | string[])[];
            /** Pre Major Math */
            pre_major_math: (string | string[])[];
            /** Pre Major Stats */
            pre_major_stats: (string | string[])[];
            /** Pre Major Science */
            pre_major_science: string[][];
            /** Major Cs Core */
            major_cs_core: (string | string[])[];
            /** Major Ee */
            major_ee: (string | string[])[];
            major_technical_electives: components["schemas"]["TechnicalElectives"];
            /** Electives Options */
            electives_options?: string[];
        };
        /** ScheduleModifyRequest */
        ScheduleModifyRequest: {
            /** Modify Intent */
            modify_intent: string;
            current_plan: components["schemas"]["PlanJSON"];
            student_state: components["schemas"]["StudentState"];
            requirements_map: components["schemas"]["RequirementsMap"];
            /** Career Goal */
            career_goal: string;
            /** Hard Courses */
            hard_courses: components["schemas"]["CourseNode"][];
            other_must_reqs: components["schemas"]["OtherRequirements"];
            /** Ge Placeholders Remaining */
            ge_placeholders_remaining: string[];
            /** Scored Electives */
            scored_electives: components["schemas"]["ScoredCourse"][];
            /** Scored Enrichment */
            scored_enrichment: components["schemas"]["ScoredCourse"][][];
        };
        /** ScheduleModifyResponse */
        ScheduleModifyResponse: {
            new_plan: components["schemas"]["PlanJSON"];
            /** Diff Label */
            diff_label: string;
            /** Schedule Remarks */
            schedule_remarks: string[];
        };
        /**
         * ScoredCourse
         * @description A course paired with a career-goal alignment score.
         *
         *     Score is a property of (course × career_goal), not of the course alone —
         *     the same CourseNode can have different scores for different career goals.
         *
         *     For electives: score derived from ChromaDB L2 distance via 1/(1+distance).
         *     For enrichment: score assigned by enrichment_rerank_node (Gemini Flash, 0.0–1.0).
         *     For enrichment prereq chains: score inherited from the primary dependent course.
         */
        ScoredCourse: {
            course: components["schemas"]["CourseNode"];
            /** Score */
            score: number;
        };
        /**
         * SemesterPlan
         * @description One semester in the final PlanJSON.
         */
        SemesterPlan: {
            /** Label */
            label: string;
            /** Semester Index */
            semester_index: number;
            /** Is Completed */
            is_completed: boolean;
            /** Total Units */
            total_units: number;
            /** Courses */
            courses: components["schemas"]["PlannedCourse"][];
        };
        /** StarsResponse */
        StarsResponse: {
            student_state: components["schemas"]["StudentState"];
            student_state_summary: components["schemas"]["StudentStateSummary"];
            requirements_map: components["schemas"]["RequirementsMap"];
        };
        /** StudentException */
        StudentException: {
            /**
             * Code
             * @enum {string}
             */
            code: "CW" | "RA" | "RE" | "RW" | "UW";
            /** Course Code */
            course_code: string;
            /** Note */
            note: string;
        };
        /** StudentState */
        StudentState: {
            /** Name */
            name: string;
            class_level: components["schemas"]["ClassLevel"];
            /** Entrance Term */
            entrance_term: string;
            /** Expected Graduation */
            expected_graduation: string;
            /** Major */
            major: string;
            /** Degree */
            degree: string;
            /** Minor */
            minor?: string | null;
            /**
             * Pdp
             * @default false
             */
            pdp: boolean;
            /** Pdp Degree */
            pdp_degree?: string | null;
            /**
             * Pdp Reflected In Stars
             * @default false
             */
            pdp_reflected_in_stars: boolean;
            /** Units Earned */
            units_earned: number;
            /** Units In Process */
            units_in_process: number;
            /** Units Needed */
            units_needed: number;
            /** Units Transfer */
            units_transfer: number;
            /** Residency Units Earned */
            residency_units_earned: number;
            /** Residency Units In Process */
            residency_units_in_process: number;
            /** Residency Satisfied */
            residency_satisfied: boolean;
            /** Upper Division Units Earned */
            upper_division_units_earned: number;
            /** Upper Division Units In Process */
            upper_division_units_in_process: number;
            /** Upper Division Units Needed */
            upper_division_units_needed: number;
            /** Remaining Semesters Estimate */
            remaining_semesters_estimate: number;
            /** Free Elective Units */
            free_elective_units: number;
            /** Ge Completion */
            ge_completion?: {
                [key: string]: components["schemas"]["GECategoryStatus"];
            };
            /** Major Requirements Status */
            major_requirements_status?: {
                [key: string]: components["schemas"]["SubRequirementStatus"];
            };
            /** Writing Requirement Satisfied */
            writing_requirement_satisfied: boolean;
            /** Ge Seminar Satisfied */
            ge_seminar_satisfied: boolean;
            /** Courses Taken */
            courses_taken?: components["schemas"]["CourseRecord"][];
            /** Current Registration */
            current_registration?: string[];
            /** Exception Codes */
            exception_codes?: components["schemas"]["StudentException"][];
        };
        /** StudentStateSummary */
        StudentStateSummary: {
            /** Name */
            name: string;
            class_level: components["schemas"]["ClassLevel"];
            /** Entrance Term */
            entrance_term: string;
            /** Expected Graduation */
            expected_graduation: string;
            /** Major */
            major: string;
            /** Degree */
            degree: string;
            /** Minor */
            minor: string | null;
            /** Units Earned */
            units_earned: number;
            /** Units In Process */
            units_in_process: number;
            /** Units Needed */
            units_needed: number;
            /** Units Transfer */
            units_transfer: number;
            /** Residency Units Earned */
            residency_units_earned: number;
            /** Residency Units In Process */
            residency_units_in_process: number;
            /** Residency Satisfied */
            residency_satisfied: boolean;
            /** Upper Division Units Earned */
            upper_division_units_earned: number;
            /** Upper Division Units In Process */
            upper_division_units_in_process: number;
            /** Upper Division Units Needed */
            upper_division_units_needed: number;
            /** Major Requirements Status */
            major_requirements_status: {
                [key: string]: components["schemas"]["SubRequirementStatus"];
            };
            /** Writing Requirement Satisfied */
            writing_requirement_satisfied: boolean;
            /** Ge Seminar Satisfied */
            ge_seminar_satisfied: boolean;
        };
        /** SubRequirementStatus */
        SubRequirementStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "met" | "unmet" | "in_progress";
            /** Courses Taken */
            courses_taken?: string[];
            /** Units Earned */
            units_earned: number;
            /** Units Needed */
            units_needed: number;
            /** Courses Needed */
            courses_needed: number;
        };
        /** TechnicalElectives */
        TechnicalElectives: {
            /** Min Units */
            min_units: number;
            /** Min Courses */
            min_courses: number;
            /** Level Minimum */
            level_minimum: number;
            /** Dept Primary */
            dept_primary: string;
            /** Note */
            note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    parse_stars_api_stars_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_stars_api_stars_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StarsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_pipeline_api_pipeline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modify_schedule_api_schedule_modify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleModifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleModifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
